### ISSUE TITLE
QA Applying "in-review" label triggers call dwyl/time API to start Timer

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwylbot#20] opened 2017-03-10 15:51 UTC
> As a QA reviewing _many_ Pull Requests per day
I would *love* my act of applying the `in-review` label to a PR to start my Timer
So that it counts how long I've been reviewing the PR and I don't have to _manually_ select the project and click "start".

Ideally the timer should be _stopped_ when the PR is Merged or `in-review` label removed and assigned back to the person who _created_ the PR.

At present I a _manually_ click "Start Timer" after I have applied the `in-review` label.
If we are going to _scale_ the review of code we need a way of automatically starting Timers.
This functionality will also apply to `in-progress` #7

**Comment by ghost** [comment] 2017-05-10 09:43
@nelsonic is this part of the time app or dwylbot?

**Comment by iteles** [comment] 2017-05-11 09:42
@markwilliamfirth The trigger mentioned in this issue needs to come from dwylbot.

This cannot be done until there _is_ an API to make a call to so I would suggest adding an `external-dependency` label to this one and bumping down the priority.

**Comment by ghost** [comment] 2017-05-11 09:53
I didn't think we were allowed external-dependency labels in dev repos 😛

**Comment by ghost** [comment] 2017-06-19 10:34
@iteles could Time not utilise the same API that dwylbot is utilising in order to know when the "in-review" label is applied?

**Comment by ghost** [comment] 2017-08-09 18:48
Closing as duplicate of https://github.com/dwyl/dwylbot/issues/120#issuecomment-310428431

**Closed as completed by ghost** 2017-08-09 18:48 UTC
Labels: enhancement, help wanted, priority-3, dependency
