### ISSUE TITLE
Amend markdown error on time estimation dwylbot comment

### ISSUE THREAD

**Issue by Cleop** [dwyl/dwylbot#114] opened 2017-06-21 09:59 UTC
The dwylbot comment for #61, an issue that is in-progress but with no time estimation is currently:
![image](https://user-images.githubusercontent.com/16775804/27378555-2eb7d990-5670-11e7-9337-a547b4183227.png)

The backtick on the last `in-progress` is too far and has covered the word label, move this for consistency so it looks the same as the first one.

**Comment by SimonLab** [comment] 2017-06-21 10:07
@Cleop the issue is in "awaiting-review" but it doesn't seem to have a PR open linked to the issue, is this right?

**Comment by Cleop** [comment] 2017-06-21 11:00
Sorry, I hadn't pushed up but had put awaiting review because it was no longer in-progress. Try now 😊

**Comment by SimonLab** [comment] 2017-06-21 11:16
Good user testing, I think if the issue is no longer in progress we should just remove the "in-progress" label and only add the "awaiting-review" when the PR is ready. But maybe my definition of "awaiting-review" on issue is not right, what do you think?

**Comment by Cleop** [comment] 2017-06-21 11:22
I agree that my use of the `awaiting-review` label in that context is perhaps a little misleading. However, the reason I do it is because I don't want to ruin the time estimates recorded using in-progress and if I leave the issue with no progress labels at all, I find it more work to go back in and assign `awaiting-review` manually later. Whereas if I remove `in-progress` and switch straight to `awaiting-review` then I've smoothed that action into one visit to the issue (which if you have a lot of issues can be time consuming). I know you can tick multiple issues and change their labels at a time but then I find it hard remembering / altering the correct labels and not missing any out. Obviously you can look at the issues mentioned by number in your PR, but if dwylbot could help me not have to open those tabs again and change them, I would find this very useful!

**Comment by ghost** [comment] 2017-08-09 18:31
Closing as this was merged

**Closed as completed by ghost** 2017-08-09 18:31 UTC
Labels: bug, awaiting-review, T25m, user-feedback
